default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: foreignernetwork_development

test:
  <<: *default
  database: foreignernetwork_test

production:
  <<: *default
  database: foreignernetwork_production
  username: foreignernetwork
  password: <%= ENV['FOREIGNERNETWORK_DATABASE_PASSWORD'] %>
