# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




# ADD COUNTRIES
Username.create(name: '')
Userlastname.create(lastname: '')
Relationship.create(relationshipname: '- not selected -')
Relationship.create(relationshipname: 'In a relationship')
Relationship.create(relationshipname: 'Engaged')
Relationship.create(relationshipname: 'Married')
Relationship.create(relationshipname: 'In love')
Relationship.create(relationshipname: 'Complicated')
Relationship.create(relationshipname: 'Actively searching')
Relationship.create(relationshipname: 'I love God')
Gender.create(gendername: '- not selected -')
Gender.create(gendername: 'Male')
Gender.create(gendername: 'Female')
City.create(cityname: '- not entered -', country_id: 1)
Country.create(countryname: '- not selected -')
Country.create(countryname: 'Afghanistan')
Country.create(countryname: 'Albania')
Country.create(countryname: 'Algeria')
Country.create(countryname: 'Andorra')
Country.create(countryname: 'Angola')
Country.create(countryname: 'Antigua & Deps')
Country.create(countryname: 'Argentina')
Country.create(countryname: 'Armenia')
Country.create(countryname: 'Australia')
Country.create(countryname: 'Austria')
Country.create(countryname: 'Azerbaijan')
Country.create(countryname: 'Bahamas')
Country.create(countryname: 'Bahrain')
Country.create(countryname: 'Bangladesh')
Country.create(countryname: 'Barbados')
Country.create(countryname: 'Belarus')
Country.create(countryname: 'Belgium')
Country.create(countryname: 'Belize')
Country.create(countryname: 'Benin')
Country.create(countryname: 'Bhutan')
Country.create(countryname: 'Bolivia')
Country.create(countryname: 'Bosnia Herzegovina')
Country.create(countryname: 'Botswana')
Country.create(countryname: 'Brazil')
Country.create(countryname: 'Brunei')
Country.create(countryname: 'Bulgaria')
Country.create(countryname: 'Burkina')
Country.create(countryname: 'Burundi')
Country.create(countryname: 'Cambodia')
Country.create(countryname: 'Cameroon')
Country.create(countryname: 'Canada')
Country.create(countryname: 'Cape Verde')
Country.create(countryname: 'Central African Rep')
Country.create(countryname: 'Chad')
Country.create(countryname: 'Chile')
Country.create(countryname: 'China')
Country.create(countryname: 'Colombia')
Country.create(countryname: 'Comoros')
Country.create(countryname: 'Congo')
Country.create(countryname: 'Congo {Democratic Rep}')
Country.create(countryname: 'Costa Rica')
Country.create(countryname: 'Croatia')
Country.create(countryname: 'Cuba')
Country.create(countryname: 'Cyprus')
Country.create(countryname: 'Czech Republic')
Country.create(countryname: 'Denmark')
Country.create(countryname: 'Djibouti')
Country.create(countryname: 'Dominica')
Country.create(countryname: 'Dominican Republic')
Country.create(countryname: 'East Timor')
Country.create(countryname: 'Ecuador')
Country.create(countryname: 'Egypt')
Country.create(countryname: 'El Salvador')
Country.create(countryname: 'Equatorial Guinea')
Country.create(countryname: 'Eritrea')
Country.create(countryname: 'Estonia')
Country.create(countryname: 'Ethiopia')
Country.create(countryname: 'Fiji')
Country.create(countryname: 'Finland')
Country.create(countryname: 'France')
Country.create(countryname: 'Gabon')
Country.create(countryname: 'Gambia')
Country.create(countryname: 'Georgia')
Country.create(countryname: 'Germany')
Country.create(countryname: 'Ghana')
Country.create(countryname: 'Greece')
Country.create(countryname: 'Grenada')
Country.create(countryname: 'Guatemala')
Country.create(countryname: 'Guinea')
Country.create(countryname: 'Guinea-Bissau')
Country.create(countryname: 'Guyana')
Country.create(countryname: 'Haiti')
Country.create(countryname: 'Honduras')
Country.create(countryname: 'Hungary')
Country.create(countryname: 'Iceland')
Country.create(countryname: 'India')
Country.create(countryname: 'Indonesia')
Country.create(countryname: 'Iran')
Country.create(countryname: 'Iraq')
Country.create(countryname: 'Ireland {Republic}')
Country.create(countryname: 'Israel')
Country.create(countryname: 'Italy')
Country.create(countryname: 'Ivory Coast')
Country.create(countryname: 'Jamaica')
Country.create(countryname: 'Japan')
Country.create(countryname: 'Jordan')
Country.create(countryname: 'Kazakhstan')
Country.create(countryname: 'Kenya')
Country.create(countryname: 'Kiribati')
Country.create(countryname: 'Korea North')
Country.create(countryname: 'Korea South')
Country.create(countryname: 'Kosovo')
Country.create(countryname: 'Kuwait')
Country.create(countryname: 'Kyrgyzstan')
Country.create(countryname: 'Laos')
Country.create(countryname: 'Latvia')
Country.create(countryname: 'Lebanon')
Country.create(countryname: 'Lesotho')
Country.create(countryname: 'Liberia')
Country.create(countryname: 'Libya')
Country.create(countryname: 'Liechtenstein')
Country.create(countryname: 'Lithuania')
Country.create(countryname: 'Luxembourg')
Country.create(countryname: 'Macedonia')
Country.create(countryname: 'Madagascar')
Country.create(countryname: 'Malawi')
Country.create(countryname: 'Malaysia')
Country.create(countryname: 'Maldives')
Country.create(countryname: 'Mali')
Country.create(countryname: 'Malta')
Country.create(countryname: 'Marshall Islands')
Country.create(countryname: 'Mauritania')
Country.create(countryname: 'Mauritius')
Country.create(countryname: 'Mexico')
Country.create(countryname: 'Micronesia')
Country.create(countryname: 'Moldova')
Country.create(countryname: 'Monaco')
Country.create(countryname: 'Mongolia')
Country.create(countryname: 'Montenegro')
Country.create(countryname: 'Morocco')
Country.create(countryname: 'Mozambique')
Country.create(countryname: 'Myanmar')
Country.create(countryname: 'Namibia')
Country.create(countryname: 'Nauru')
Country.create(countryname: 'Nepal')
Country.create(countryname: 'Netherlands')
Country.create(countryname: 'New Zealand')
Country.create(countryname: 'Nicaragua')
Country.create(countryname: 'Niger')
Country.create(countryname: 'Nigeria')
Country.create(countryname: 'Norway')
Country.create(countryname: 'Oman')
Country.create(countryname: 'Pakistan')
Country.create(countryname: 'Palau')
Country.create(countryname: 'Panama')
Country.create(countryname: 'Papua New Guinea')
Country.create(countryname: 'Paraguay')
Country.create(countryname: 'Peru')
Country.create(countryname: 'Philippines')
Country.create(countryname: 'Poland')
Country.create(countryname: 'Portugal')
Country.create(countryname: 'Qatar')
Country.create(countryname: 'Romania')
Country.create(countryname: 'Russian Federation')
Country.create(countryname: 'Rwanda')
Country.create(countryname: 'St Kitts & Nevis')
Country.create(countryname: 'St Lucia')
Country.create(countryname: 'Saint Vincent & the Grenadines')
Country.create(countryname: 'Samoa')
Country.create(countryname: 'San Marino')
Country.create(countryname: 'Sao Tome & Principe')
Country.create(countryname: 'Saudi Arabia')
Country.create(countryname: 'Senegal')
Country.create(countryname: 'Serbia')
Country.create(countryname: 'Seychelles')
Country.create(countryname: 'Sierra Leone')
Country.create(countryname: 'Singapore')
Country.create(countryname: 'Slovakia')
Country.create(countryname: 'Slovenia')
Country.create(countryname: 'Solomon Islands')
Country.create(countryname: 'Somalia')
Country.create(countryname: 'South Africa')
Country.create(countryname: 'South Sudan')
Country.create(countryname: 'Spain')
Country.create(countryname: 'Sri Lanka')
Country.create(countryname: 'Sudan')
Country.create(countryname: 'Suriname')
Country.create(countryname: 'Swaziland')
Country.create(countryname: 'Sweden')
Country.create(countryname: 'Switzerland')
Country.create(countryname: 'Syria')
Country.create(countryname: 'Taiwan')
Country.create(countryname: 'Tajikistan')
Country.create(countryname: 'Tanzania')
Country.create(countryname: 'Thailand')
Country.create(countryname: 'Togo')
Country.create(countryname: 'Tonga')
Country.create(countryname: 'Trinidad & Tobago')
Country.create(countryname: 'Tunisia')
Country.create(countryname: 'Turkey')
Country.create(countryname: 'Turkmenistan')
Country.create(countryname: 'Tuvalu')
Country.create(countryname: 'Uganda')
Country.create(countryname: 'Ukraine')
Country.create(countryname: 'United Arab Emirates')
Country.create(countryname: 'United Kingdom')
Country.create(countryname: 'United States')
Country.create(countryname: 'Uruguay')
Country.create(countryname: 'Uzbekistan')
Country.create(countryname: 'Vanuatu')
Country.create(countryname: 'Vatican City')
Country.create(countryname: 'Venezuela')
Country.create(countryname: 'Vietnam')
Country.create(countryname: 'Yemen')
Country.create(countryname: 'Zambia')
Country.create(countryname: 'Zimbabwe')